### ISSUE TITLE
Deprecated version of the Android embedding

### ISSUE THREAD

**Issue by An1metall** [wooxist/unique_ids#3] opened 2021-09-10 08:03 UTC
Hi!

After the update to Flutter 2.5.0, when calling `flutter pub get` began to receive the following message:

The plugin `unique_ids` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by oshuam** [comment] 2021-09-12 22:57
Confirmed the same issue after upgrading to flutter version 2.5.0.

**Comment by wooxist** [comment] 2021-09-14 02:40
It'll be fixed in today.

**Comment by wooxist** [comment] 2021-09-14 04:14
It's fixed.
Please update to 3.0.0

**Closed** 2021-09-14 04:14 UTC

**Comment by oshuam** [comment] 2021-09-14 14:47
Works for me! Thanks!
